services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./Ollama/ollama_data:/root/.ollama_data
      - ./Ollama/ollama:/root/.ollama
      - ./Models:/models
    deploy:
     resources:
      limits:
       cpus: 4
       memory: 8G

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_HOST=0.0.0.0:8080
    depends_on:
      - ollama

volumes:
  ollama_data:
